### ISSUE TITLE
Could not get a resource from the pool

### ISSUE THREAD

**Issue by ilzming** [ScienJus/spring-authorization-manager#1]
redis-server显示 1 clients connected，但是jedis = jedisPool.getResource();之后jedis还是null，然后异常是"Could not get a resource from the pool"。不知道碰到过没有？

**Comment by ScienJus** [comment]
请问是必然发生还是在比较频繁的时候才会发生？这个看上去是Jedis本身配置的问题，请尝试增加timeout时长或是连接数再进行尝试、

**Comment by ilzming** [comment]
第一次调用就发生。。。。timeout已经很长了，现在也只有我自己连接

**Comment by ScienJus** [comment]
我这里对Redis的操作都是直接调用的Jedis的方法，还请再看一下Jedis和Redis的配置。如果直接在程序中使用同一个JedisPool做一些操作也不会报错么？

**Comment by ilzming** [comment]
直接调用是没错的，/(ㄒoㄒ)/~~

**Comment by ScienJus** [comment]
比较纠结的是，这个异常无法提供一些有效信息，所以会有很多可能产生错误的原因。而且同一个JedisPool实例直接调用没有问题，在我的代码中调用就有问题更是匪夷所思。

如果有能力的话，请先不要配置拦截器和解析器，仅仅使用RedisTokenManager和JedisPool进行一些操作，并观察连接池的状态。另外我刚才提交了一些关于RedisTokenManager的测试用例，你也可以尝试一下修改为本地的配置看看能否跑通。

**Comment by ilzming** [comment]
我用单例模式写了，哎项目紧，，，，，，再问大牛一个问题，项目中自定义拦截器，就像给的代码中，perHandle方法中，用request.setAttribute("x","y")（这个时候再用request.getParameter("x")也是null），咋到了具体方法中用request.getParameter("x")获取不到值喃？

**Comment by ScienJus** [comment]
Attribute和Parameter是两个域，得用getAttribute取。仔细看一下可以发现 getAttribute返回Object类型，getParameter返回String类型。

**Comment by ilzming** [comment]
受教了，谢谢啊，该学的东西还有很多啊
